name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: renn_ai
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/renn_ai
      JWT_SECRET: testsecretjwt
      WEBHOOK_SECRET: testsecretwebhook
      ALLOWED_ORIGINS: http://localhost:3000
      PG_SSL: 'false'
      REDIS_URL: redis://localhost:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build
      - name: Migrate and seed
        run: |
          npm run db:migrate
          npm run migrate:pg:up
          npm run db:seed || true
          node scripts/seed-preview.js || true
      - name: Run smoke tests
        run: npm run smoke:direct || npm run smoke
      - name: Run test suite
        run: npm test
      - name: Generate API docs
        run: |
          npm run schemas
          npm run openapi
      - name: Upload preview artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preview-artifacts
          path: |
            coverage
            public/dist
            lhr*.json
            docs/api-schemas.json
            docs/openapi.json
      - name: Note preview deployment (optional)
        if: ${{ secrets.PREVIEW_URL != '' }}
        run: |
          echo "Preview URL: ${{ secrets.PREVIEW_URL }}"
          echo "Set PREVIEW_URL secret to surface a real preview endpoint."
